version: '3'

services:
  postgres-locking-db:
    image: "postgres"
    container_name: postgres-locking-db-container
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data:delegated"
    ports:
      - "5499:5432"

  postgres-locking-test:
    image: node:12-alpine
    working_dir: /app
    command: sh -c "yarn install --ignore-optional && yarn run dev"
    container_name: postgres-locking-test-container
    volumes:
      - './:/app:cached'
      - /app/node_modules
    ports:
      - '9000:80'
    depends_on:
      - postgres-locking-db
